name: Build and Deploy Android App

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: "New Android Release"
        description: "Release notes for this build"

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Build AAB
        run: eas build --platform android --profile production --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Download Artifact
        run: |
          mkdir -p dist
          eas build:list --platform android --status finished --json | jq -r '.[0].artifacts.buildUrl' | xargs curl -o dist/app-release.aab
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: dist/app-release.aab
          releaseNotes: ${{ inputs.release_notes }}
